### ISSUE TITLE
Question about the alignment between ROMP and Colmap

### ISSUE THREAD

**Issue by LarkLeeOnePiece** [apple/ml-hugs#13]
I have a question about the alignment between Colmap and ROMP. Since the motion paramters are predicted by ROMP which represent the parameters based on the camera coordination and it assume the camera extrinsic parameters are const(static monocular). However, when you use the Colmap to estimate the extrinsic parameters of the camera. They are in different world coordination. How do you align they?

Should we find the alignment for each camera extrinsic between colmap and ROMP if we have the SFM data?

**Comment by LarkLeeOnePiece** [comment]
Add more description:
Based on my understanding, we can have the motion parameters from ROMP. The motion includes the body shape and the body pose based on the camera coordination.
However, when we render one image using this algorithm, we use the camera from colmap, right? If so, the intrinsic parameters are the same（or similar） between ROMP and Colmap. But with respect to the extrinsic parameters, that's totally different. And we initialize the human_gs in canonical space(which is in camera space,right?) and then use LBS to transform the canoinical huamn to the expected pose(Also in camera space, right?).  However, up to now, the human_gs points are still not in the world coordination unless you have the alignment between ROMP and Colmap.
Based on your paper and Neuman, you only discuss the alignment when we have the novel pose and view. Did you align the pose during the data pre-processing or you use the network to predict the delta mean shifts as the alignment?  Could you explain more about the coordination for me?
I would appreciate it if you can help me.

**Comment by ZCWzy** [comment]
During data preprocessing, the smpl was transferred from the predictive coordinate system（ROMP or 4D-human） to the world coordinate system (colmap).
