### ISSUE TITLE
[bugs] Using SMPL-v1.1.0 with 300 shape pcs can't run train or evaluation successfully

### ISSUE THREAD

**Issue by Owen-Fish** [apple/ml-hugs#3]
I am very happy to be open source. I found two problems during the execution of the code.
1. using SMPL-v1.1.0 with 300 shapes can't run successfully with such RuntimeError:
<img width="1254" alt="image" src="https://github.com/apple/ml-hugs/assets/39903624/581e80ea-f9cc-4df3-93cb-aa6250dcbc3d">
The reason for this error is that the dimensions of betas read from the /data/neuman/dataset are only 10, which does not match the recommended smpl-v1.1.0 which has 300 dims PCs. 

**[qiuck fix]** **use SMPL-V1.0.0 is OK**
2. Inconsistency between keywords in configfile and code. 
<img width="1117" alt="image" src="https://github.com/apple/ml-hugs/assets/39903624/6f2f7653-b59c-455a-99e9-1778d1635cb1">
**[quick fix]**  Just make sure that the keyword **cfg.human.name** is consistent in the configfile and code.

**Comment by mkocabas** [comment]
@Owen-Fish thanks for reporting this. You can check my latest PR here https://github.com/apple/ml-hugs/pull/4 to get rid of the first issue.
